/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/pages/domain`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/natural`; params?: Router.UnknownInputParams; } | { pathname: `/pages/plastic`; params?: Router.UnknownInputParams; } | { pathname: `/pages/scan`; params?: Router.UnknownInputParams; } | { pathname: `/pages/tamilnadu`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/domain`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/natural`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/plastic`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/tamilnadu`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/pages/domain${`?${string}` | `#${string}` | ''}` | `/pages/login${`?${string}` | `#${string}` | ''}` | `/pages/natural${`?${string}` | `#${string}` | ''}` | `/pages/plastic${`?${string}` | `#${string}` | ''}` | `/pages/scan${`?${string}` | `#${string}` | ''}` | `/pages/tamilnadu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/pages/domain`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/natural`; params?: Router.UnknownInputParams; } | { pathname: `/pages/plastic`; params?: Router.UnknownInputParams; } | { pathname: `/pages/scan`; params?: Router.UnknownInputParams; } | { pathname: `/pages/tamilnadu`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
